# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180402_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('message', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
